# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - productservice-onlineshop

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_57d8695d422a41dc83146a1ab773d566 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_836398d4aed34819bd150d01508ba548 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_57d8695d422a41dc83146a1ab773d566 }}/semm12/productservice-webshop:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'productservice-onlineshop'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c646ab23636147e7bf96cfe04639add6 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_57d8695d422a41dc83146a1ab773d566 }}/semm12/productservice-webshop:${{ github.sha }}'